### ISSUE TITLE
Request: RNG builtin

### ISSUE THREAD

**Issue by p-e-w** [curv3d/curv#59] opened 2019-01-19 05:19 UTC
It would be helpful both for constructing shapes and for testing if Curv had a built-in random number generator. A simple `rnd()` function that returns a uniform float from `[0,1]` should suffice for most use cases.

Curv doesn't have global mutable state so it is quite inconvenient to implement this in the language itself. Therefore, a builtin looks like the best solution here. A nice extra would be the ability to optionally seed the generator with a fixed value passed as a command line argument; this would enable reproducible output.

**Comment by doug-moen** [comment] 2019-01-19 11:44
Curv is a pure functional language by design. An `rng()` function that returns a different value on each call would implicitly refer to global mutable state, and that would ruin the pure functional nature of Curv.

Curv is a pure functional language for several reasons. One reason is that it is not feasible to evaluate calls to a function like `rng()` on a GPU, due to the absence of any practical implementation of global mutable state on a GPU. Another reason is the compiler. I am planning to implement optimizations like common subexpression elimination that depend on the fact that all functions are pure. A third reason is human factors: pure functional languages are inherently simple, and it is easier for humans to reason about the meaning of a program if the result of a function call depends only on the argument value.

I am indeed thinking about adding a built-in 'random number generator', but this will actually be a hash function that maps its argument onto a uniform float in the range [0,1]. When you are coding a 3D `dist` function or a `colour` function within a shape, it is common practice to hash the [x,y,z] coordinates of the point you are working on to create a random value.

There are already examples of this style of coding in the examples directory, using 'random number' hash functions written in Curv. In `finial.curv` written by @TLC123, there is:
```
arandom aseed = frac(sin(dot((aseed,aseed), (12.9898,78.233)))*43758.5453123);
```
In `smoke.curv`, there is:
```
random xy = frac(sin(dot(xy, (12.9898,78.233)))*43758.5453123);
```

**Comment by p-e-w** [comment] 2019-01-21 06:39
Hash functions that yield pseudorandom output on some input domain can indeed solve this problem, but it's quite cumbersome to choose and pass in an appropriate argument on each invocation.

Alas, with some help from the compiler, this burden could be eliminated and a familiar argument-less `rnd()` function be provided *without* sacrificing the purely functional nature of Curv.

To achieve this, the compiler (or a preprocessor) would need to expand `rnd()` calls with arguments, namely:

* The character offset of the call in the source code, and
* all variables/function arguments that are in scope.

That is, for example,

```
let
a = 1;
b = rnd();
in
rnd()
```

becomes something like

```
let
a = 1;
b = rnd(15, a);
in
rnd(29, a, b)
```

with the value of `rnd` depending only on its arguments. This combines the convenience of a traditional `rnd` function as provided by imperative languages with the advantages of fully deterministic output. "Seeding" the PRNG is as simple as declaring any variable in a `let` construct wrapping the rest of the code.

**Comment by doug-moen** [comment] 2019-11-23 02:30
There is a new 'noise' library under construction that contains random number generators (actually, hash functions). I just checked in the first code for this. For now, see `examples/noise.curv`.

**Closed by doug-moen** 2019-11-23 02:30 UTC
